### PR TITLE
Update fixlayouts.cpp

### PR DESCRIPTION
**Pull request by justanotheranonymoususer**
Always restore clipboard data, even if there's a timeout.

### CODE REVIEW

**Comment by finereli** [comment]
Looks OK to me. Did you encounter a specific issue that gave rise to this fix?

**Comment by justanotheranonymoususer** [comment]
I've encountered many issues, and fixed many of them.
My fork here has many changes and some new features:
https://github.com/justanotheranonymoususer/recaps

As of now, the number one issue that I don't know how to solve is that Skype and Word hang when switching languages with recaps. I don't care that much for Skype, but for Word, that really sucks.

**Comment by finereli** [comment]
Oh my god!

This is incredible, I never thought anybody would actually take this code
and work with it. Win32 has become way more obscure since the time I
originally worked on Recaps and I haven't used Windows for a few years so I
couldn't fix any of the issues.

I've heard multiple times about the Skype and Word crashes. Did you try to
reduce the features, remove code until it doesn't crash Word? Maybe keep
the hook in, but avoid actually switching the language or removing the
language correction functionality?

Anyway, you're more than welcome to take over the repo, and I can't point
the visitors at my repo over to you.

Thanks for taking this up, it means so very much to me!

Let me know if I can help you with anything.

Thanks,
Eli

**Comment by justanotheranonymoususer** [comment]
> Did you try to reduce the features, remove code until it doesn't crash Word?

I know exactly what causes it: posting `WM_INPUTLANGCHANGEREQUEST` makes the programs hang.
Relevant post [here](http://stackoverflow.com/questions/27720728/cant-send-wm-inputlangchangerequest-to-some-controls), without a solution.

I'm glad that you liked my fork :)

**Comment by justanotheranonymoususer** [comment]
@gooli FYI, I have hack-fixed the hang issue in my repository. It was driving me insane, but your comment made me revisit it and come up with a solution.
Thanks for the inspiration :)

**Comment by finereli** [comment]
Sure thing, I was glad to be your rubber duck :)

**Comment by finereli** [comment]
It actually looks pretty good considering the limitations. I would have
probably gone with a fixed sleep, but you're actually waiting for the app
to respond and change layout. Need to give it some time to see if it fails
under odd conditions, but it looks solid to me.​

I'd like to incorporate your changes into the main recaps repo and give you
commit permissions on it so that your work becomes part of the official
releases. What do you think?

**Comment by justanotheranonymoususer** [comment]
Thanks for the offer. I think that I'd prefer to work with the repo under my user, but of course, feel free to incorporate all of my changes, and if you'd like, you can build a release and put in [on your website](http://www.gooli.org/blog/recaps/).

**Pull request merged**
